# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1643, 1014)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 20, 441, 901))
        self.listWidget.setStyleSheet("QListWidget{background-color: rgb(247, 247, 247); color:rgb(51,51,51); border: 1px solid  rgb(247, 247, 247);outline:0px;}\n"
"QListWidget::Item{background-color: rgb(247, 247, 247);}\n"
"QListWidget::Item:hover{background-color: rgb(247, 247, 247); }\n"
"QListWidget::item:selected{\n"
"    background-color: rgb(247, 247, 247);\n"
"    color:black; \n"
"    border: 1px solid  rgb(247, 247, 247);\n"
"}\n"
"QListWidget::item:selected:!active{border: 1px solid  rgb(247, 247, 247); background-color: rgb(247, 247, 247); color:rgb(51,51,51); } ")
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setObjectName("listWidget")
        self.cleartrackbutton = QtWidgets.QPushButton(self.centralwidget)
        self.cleartrackbutton.setGeometry(QtCore.QRect(470, 890, 1151, 35))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cleartrackbutton.setFont(font)
        self.cleartrackbutton.setAutoFillBackground(False)
        self.cleartrackbutton.setStyleSheet("border-radius:6px;\n"
"padding:2px 4px;\n"
"border-style: outset;\n"
"border:2px groove gray;\n"
"background-color: rgb(229, 234, 233);\n"
"color: rgb(37, 194, 118);")
        self.cleartrackbutton.setObjectName("cleartrackbutton")
        self.map_view_mini = QtWidgets.QGraphicsView(self.centralwidget)
        self.map_view_mini.setGeometry(QtCore.QRect(460, 20, 381, 301))
        self.map_view_mini.setObjectName("map_view_mini")
        self.map_view_real = QtWidgets.QGraphicsView(self.centralwidget)
        self.map_view_real.setGeometry(QtCore.QRect(460, 320, 1141, 551))
        self.map_view_real.setObjectName("map_view_real")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1643, 23))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTool = QtWidgets.QMenu(self.menubar)
        self.menuTool.setObjectName("menuTool")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_open_map = QtWidgets.QAction(MainWindow)
        self.action_open_map.setObjectName("action_open_map")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        self.actionTag_location = QtWidgets.QAction(MainWindow)
        self.actionTag_location.setObjectName("actionTag_location")
        self.actionadd_preson = QtWidgets.QAction(MainWindow)
        self.actionadd_preson.setObjectName("actionadd_preson")
        self.actionsave_Tag_Location = QtWidgets.QAction(MainWindow)
        self.actionsave_Tag_Location.setObjectName("actionsave_Tag_Location")
        self.actionsave_mapView = QtWidgets.QAction(MainWindow)
        self.actionsave_mapView.setObjectName("actionsave_mapView")
        self.actionshowRoomLabel = QtWidgets.QAction(MainWindow)
        self.actionshowRoomLabel.setObjectName("actionshowRoomLabel")
        self.menuFile.addAction(self.action_open_map)
        self.menuFile.addAction(self.actionsave_Tag_Location)
        self.menuFile.addAction(self.actionsave_mapView)
        self.menuFile.addAction(self.action_exit)
        self.menuTool.addAction(self.actionTag_location)
        self.menuTool.addAction(self.actionadd_preson)
        self.menuView.addAction(self.actionshowRoomLabel)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTool.menuAction())
        self.menubar.addAction(self.menuView.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FIT4-5仿真平台"))
        self.cleartrackbutton.setText(_translate("MainWindow", "Clear the Track"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuTool.setTitle(_translate("MainWindow", "Tool"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.action_open_map.setText(_translate("MainWindow", "&open_map"))
        self.action_exit.setText(_translate("MainWindow", "&exit"))
        self.actionTag_location.setText(_translate("MainWindow", "tag_location"))
        self.actionadd_preson.setText(_translate("MainWindow", "add_preson"))
        self.actionsave_Tag_Location.setText(_translate("MainWindow", "save_Tag_Location"))
        self.actionsave_mapView.setText(_translate("MainWindow", "save_mapView"))
        self.actionshowRoomLabel.setText(_translate("MainWindow", "showRoomLabel"))
